### PR TITLE
Add Terrain page

### LINKED ISSUE #92: Add Terrain page to cover that part of the spec
This part of the style spec doesn't seem to appear anywhere in the docs

https://github.com/maplibre/maplibre-gl-js/blob/1c592d4c28f6acd55529a4a3541d255434bdbb34/src/style-spec/reference/v8.json#L3825-L3857

### PR DESCRIPTION
**Pull request by birkskyum**
Closes #92 

I also ordered the sidebar more alphabetically, except for a few special pages

Screenshot 2023-04-06 at 20 54 56

### CODE REVIEW

**Comment by HarelM** [comment]
Can you please fix the github warnings in the files tab?
Where is the terrain 3d code? I just see the title... What am I missing? 
Also I think the sdk table is producing invalid connect.
And i think the footer is linking to missing files in some pages.

**Comment by birkskyum** [comment]
It uses the Item.tsx to pull the data directly from the reference json file.

**Comment by HarelM** [comment]
The table doesn't look great in mobile and I don't understand why there are two tables here:
Screenshot_20230406_221014_Chrome

**Comment by HarelM** [comment]
Let me know if you would like me to open different issues to fix some remaining docs issues.

**Comment by birkskyum** [comment]
I added a tiny fix for the tables here

**Comment by birkskyum** [comment]
The table thing is resolved already, and unrelated to this

**Comment by HarelM** [comment]
Where is the terrain example code?

**Comment by HarelM** [comment]
Oh, this is just a reference to the terrain object page, right? Not the terrain example page...

**Review by HarelM — APPROVED** [review]

**Comment by birkskyum** [comment]
I believe It's in the gl js docs repo

**Pull request merged**
